name: test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Get current date
        run: echo "Only workflow_dispatch"
  Pull_request:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'changeset-release') && github.event.pull_request.merged
    steps:
      - name: Get current date
        run: echo "Only pull_request"
  Date:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

